name: Update Profile Cards

on:
  schedule:
    # Executa automaticamente todos os dias à meia-noite (UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: # Permite rodar manualmente no painel do GitHub

jobs:
  update-assets:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create assets directory
        run: mkdir -p assets

      - name: Download Streak SVG
        uses: wei/curl@v1
        with:
          args: -sL -A "Mozilla/5.0" "https://streak-stats.demolab.com?user=diegof856&locale=en&mode=daily&theme=radical&hide_border=false&border_radius=5&order=3" -o assets/streak.svg

      - name: Download Trophy SVG
        uses: wei/curl@v1
        with:
          args: -sL -A "Mozilla/5.0" "https://github-profile-trophy.vercel.app?username=diegof856&theme=darkhub&column=-1&row=1&margin-w=8&margin-h=8&no-bg=false&no-frame=false&order=4" -o assets/trophy.svg


      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update profile streak and trophies SVGs"
          file_pattern: 'assets/*.svg'